// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {message} from '../models';
import {config} from '../models';

export function ClearHistory():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetActiveMode():Promise<string>;

export function GetCurrentSession():Promise<main.SessionInfo>;

export function GetHistory():Promise<Array<message.Message>>;

export function GetSettings():Promise<config.Settings>;

export function GetStatus():Promise<string>;

export function GetWorkDir():Promise<string>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function NewSession(arg1:string):Promise<main.SessionInfo>;

export function PickWorkDir():Promise<string>;

export function ResizePTY(arg1:number,arg2:number):Promise<void>;

export function RestartClaude():Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SendPTYKey(arg1:string):Promise<void>;

export function SetActiveMode(arg1:string):Promise<void>;

export function SetWorkDir(arg1:string):Promise<void>;

export function SwitchSession(arg1:string):Promise<Array<message.Message>>;

export function UpdateSettings(arg1:config.Settings):Promise<void>;
