// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetCurrentSession() {
  return window['go']['main']['App']['GetCurrentSession']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetWorkDir() {
  return window['go']['main']['App']['GetWorkDir']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function PickWorkDir() {
  return window['go']['main']['App']['PickWorkDir']();
}

export function ResizePTY(arg1, arg2) {
  return window['go']['main']['App']['ResizePTY'](arg1, arg2);
}

export function RestartClaude() {
  return window['go']['main']['App']['RestartClaude']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendPTYKey(arg1) {
  return window['go']['main']['App']['SendPTYKey'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
